language: java
jdk:
- openjdk8
script: mvn clean verify

deploy:
  provider: heroku
  api_key:
  secure: TYXOeExT1p2j8VvTSCCwDQnJ1qCFbt2y9bHD11CKWI1nzuKvJP0ZlUhsks0RHWmNFYTF6LgZw8IaHTtqt8pn3STbqEfQ4OsNhlu5zewfHLkynxhOMFmJcJQtFsrsn2CuA/UmkJqCjVzW4jZOH0Kg8OdJF6cOXMRxmym8XtT3L6baGjzvOQoSNV6b3gSp4r9dr20bg6JDzuL51dmLexOhdBiOmM1CNediMf7SbR3YSsWN/SjU/UuEDeyb/IJC2+r7kRLUtSIxg93HlZcdnUjBysHszZsknhOLZvlU1IC/I3JWzBrZ00blFPTw/rC7oRw8LICzlNDKJ7H6kaVndZvjUwzhWJ9A0eHCzushY32UPerq+8B43g14Z+2OD3yDeQGW91fF9KKttqBTdYDLatZRX1WgJ+xxU93AbEChzVbl8+63MN56giWCQBLBJCuXV5XW/5k+BP6aXkbZyIPo6cvAyO6rFUG5M2addwm85REOcMNBVk8rwSfUqtRyo8HjddQA/9uPRBjsc4FYSUMgYwLnaUUJ/KaELVJFBEL5mFNJNpXH3eJOIdSIu0TrYLJ4c2cMkEgrOtGGoBP3Wtu69qvzDW9G7j+/Pl4ggzUSt6+jBHwLIwukvZPZQQ/L4M9LykYVTGENz+aX9hZVQF+A21pZ9+3wJ0ZTnTUgXCUoZrbt51I=
  app: db-cd-app
